const ActionKeys = {
  AUTH: {
    CUSTOMERINFO: 'CUSTOMERINFO'
  },
  TOKEN: {
    GET_TOKEN: 'GET_TOKEN',
    GET_EXTERNAL_TOKEN: 'GET_EXTERNAL_TOKEN'
  },
  SELECTEDOPTION: {
    SELECT: 'SELECT',
    SELECT_ADDRESS: 'SELECT_ADDRESS',
    // Personal info
    MARITAL_STATUS: 'MARITAL_STATUS',
    JOBS: 'JOBS',
    ACADEMIC_LEVEL: 'ACADEMIC_LEVEL',
    PLACE_ISSUE_CARD: 'PLACE_ISSUE_CARD',

    // Contact address
    ADDRESS_STATUS: 'ADDRESS_STATUS',
    ADDRESS_LIST: 'ADDRESS_LIST',
    ADDRESS_LIST_EXTRA: 'ADDRESS_LIST_EXTRA',
    LOAN_OBJECT: 'LOAN_OBJECT',
    TYPE_OF_IDENTIFICATION_PAPER: 'TYPE_OF_IDENTIFICATION_PAPER',

    // Reset option
    RESET_OPTION: 'RESET_OPTION'
  },
  LOAN: {
    SAVE_LOAN_DATA: 'SAVE_LOAN_DATA'
  },
  IDENTITY: {
    DATA_IDENTITY: 'DATA_IDENTITY'
  },
  PERSONAL_INFO: {
    SAVE_PERSONAL_INFO: 'SAVE_PERSONAL_INFO'
  },
  MASTER_FLOW: {
    SAVE_MASTER_FLOW: 'SAVE_MASTER_FLOW'
  },
  COMMON: {
    SET_FROM_PAGE: 'SET_FROM_PAGE'
  }
};

export default ActionKeys;
